abstract: Partty.org! interface
author: Kazuhiro Osawa <ko@yappo.ne.jp>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Net-Partty
no_index: 
  directory: 
    - inc
    - t
version: 0.01
